#!/usr/bin/env bash

set -e
json=$(curl -sS "https://graviex.net:443/api/v2/tickers/dpteth.json")
price_dpt_usd=$(jshon <<<"$json" -e ticker -e sell -u)
price_eth_usd=$(setzer price eth)

price=$(bc <<< "$price_eth_usd * $price_dpt_usd")
echo "$price"
