#!/usr/bin/env bash

set -e
json=$(curl -sS "https://api.coinmarketcap.com/v1/ticker/ethereum/")
price_eth_usd=$(jshon <<<"$json" -e 0 -e price_usd -u)

json=$(curl -sS "https://graviex.net:443/api/v2/tickers/dpteth.json")
price_dpt_usd=$(jshon <<<"$json" -e ticker -e sell -u)

price=$(bc <<< "$price_eth_usd * $price_dpt_usd")
echo "$price"
