#!/usr/bin/env python3.6

import json
from urllib import request
from decimal import Decimal

FOUR_PLACES = Decimal('.00000001')
TICKER_URL = 'https://graviex.net:443/api/v2/tickers/dpteth.json'
COINMARKET_URL = 'https://api.coinmarketcap.com/v1/ticker/ethereum/'

price_eth_usd = Decimal(json.loads(request.urlopen(COINMARKET_URL).read().decode())[0]['price_usd'])
price_dpt_eth = Decimal(json.loads(request.urlopen(TICKER_URL).read().decode())['ticker']['sell'])
print((price_eth_usd / (1 / price_dpt_eth)).quantize(FOUR_PLACES))
